# Generated by Django 4.2 on 2026-01-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_id', models.CharField(max_length=50, unique=True)),
                ('evm_id', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('ac_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['booth_id'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=10)),
                ('vote_count', models.IntegerField(default=0)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='evm.booth')),
            ],
            options={
                'unique_together': {('booth', 'candidate_id')},
            },
        ),
        migrations.CreateModel(
            name='VoteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(help_text='ms since epoch')),
                ('sequence', models.IntegerField(help_text='Vote sequence number')),
                ('voter_token_hash', models.CharField(help_text='SHA256(voter_token)', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='evm.booth')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evm.candidate')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('booth', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='VVPATSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_id', models.CharField(max_length=50, unique=True)),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='SEALED_IN_BOX', max_length=20)),
                ('vote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vvpat_slip', to='evm.voteevent')),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_signal', models.TextField(help_text='Encrypted signal from EVM')),
                ('signal_hash', models.CharField(max_length=64)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('vote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal', to='evm.voteevent')),
            ],
        ),
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('evm_count', models.IntegerField()),
                ('vvpat_count', models.IntegerField()),
                ('bam_count', models.IntegerField()),
                ('chain_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('discrepancy', models.CharField(blank=True, max_length=100)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evm.booth')),
            ],
        ),
    ]
