# Generated by Django 4.2 on 2026-02-27 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='voting_status',
            field=models.CharField(default='OPEN', max_length=20),
        ),
        migrations.CreateModel(
            name='LedgerBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField()),
                ('block_type', models.CharField(choices=[('VOTE', 'Vote Block'), ('FINAL', 'Final Block')], default='VOTE', max_length=10)),
                ('candidate_id', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.BigIntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('result_hash', models.CharField(blank=True, max_length=64)),
                ('integrity_flag', models.CharField(blank=True, max_length=10)),
                ('result_string', models.TextField(blank=True)),
                ('previous_hash', models.CharField(max_length=64)),
                ('current_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_blocks', to='evm.booth')),
            ],
            options={
                'ordering': ['block_number'],
                'unique_together': {('booth', 'block_number')},
            },
        ),
    ]
