# Generated by Django 4.2 on 2026-02-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evm', '0002_booth_voting_status_ledgerblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerblock',
            name='digital_signature',
            field=models.CharField(blank=True, help_text='HMAC-SHA256 of Final_Block_Hash using Device Private Key', max_length=64),
        ),
        migrations.AddField(
            model_name='ledgerblock',
            name='final_commitment_hash',
            field=models.CharField(blank=True, help_text='SHA256(Last_Vote_Block_Hash || Result_Hash) — binds tally to chain', max_length=64),
        ),
        migrations.AddField(
            model_name='ledgerblock',
            name='last_vote_block_hash',
            field=models.CharField(blank=True, help_text='Hash of last VOTE block (Hn) — anchor for final commitment', max_length=64),
        ),
        migrations.AddField(
            model_name='ledgerblock',
            name='tamper_block_number',
            field=models.IntegerField(blank=True, help_text='Block number where hash mismatch was detected (null = no tamper)', null=True),
        ),
    ]
